# Site settings
title: Jack Valmadre
email: jack.valmadre@gmail.com
description: "Computer vision researcher working on detection, tracking and 3D reconstruction."
baseurl: ""
url: "http://jack.valmadre.net"
twitter_username: pterojacktyl
github_username: jvlmdr

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# Content filters
future: true
